<?php
class TableNames {

	const OFERTAS = "OFERTAS";
	const OFERTAS_TEMPORALES = "OFERTAS_TEMPORALES";
	const OFERTAS_STOCK = "OFERTAS_STOCK";
	const COMPRAS = "COMPRAS";
	const CATEGORIAS_OFERTAS = "CATEGORIAS_OFERTAS";
	
}